name: NuGet Package Publish

on:
  push:
    branches:
      - main
    paths:
      - 'src/Markdown.Blog/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    # Add a condition to skip commits containing [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/Markdown.Blog

      - name: Update version and release notes
        run: |
          # Get the current version parts
          version_string=$(grep -oP '(?<=<Version>\$\(VersionPrefix\)\.)[0-9]+\.[0-9]+(?=</Version>)' src/Markdown.Blog/Markdown.Blog.csproj)
          IFS='.' read -r major minor <<< "$version_string"
          
          # Increment the minor version
          new_minor=$((minor + 1))
          
          # Update version
          sed -i "s/<Version>\$(VersionPrefix)\.$major\.$minor<\/Version>/<Version>\$(VersionPrefix).$major.$new_minor<\/Version>/" src/Markdown.Blog/Markdown.Blog.csproj

          # Update release notes
          commit_message=$(git log --no-merges -1 --pretty=%B)
          sed -i "s|<PackageReleaseNotes>.*</PackageReleaseNotes>|<PackageReleaseNotes>$commit_message</PackageReleaseNotes>|" src/Markdown.Blog/Markdown.Blog.csproj

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/Markdown.Blog/Markdown.Blog.csproj
          git commit -m "Update version and release notes [skip ci]"
          git push

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src/Markdown.Blog

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output .
        working-directory: src/Markdown.Blog

      - name: Publish to NuGet
        run: |
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push *.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        working-directory: src/Markdown.Blog
